# Generated by Django 4.1.5 on 2023-10-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerflower', '0004_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
